changes

diff --git a/start-datastore b/start-datastore
--- a/start-datastore
+++ b/start-datastore
@@ -13,26 +13,25 @@ fi
 
 options=${options:1}
 # Check for datastore options
-while [ ! $# -eq 0 ]
-do
+while [ ! $# -eq 0 ]; do
   case "$1" in
-    --store-on-disk)
-      options="$options --store-on-disk"
-      shift
-      ;;
-    --no-store-on-disk)
-      options="$options --no-store-on-disk"
-      shift
-      ;;
-    --consistency=*)
-      consistency=${1#*=}
-      options="$options --consistency=$consistency"
-      shift
-      ;;
-    *)
-      echo "Invalid option: $1. Use: --store-on-disk, --no-store-on-disk, --consistency=[0.0-1.0]"
-      exit 1
-      ;;
+  --store-on-disk)
+    options="$options --store-on-disk"
+    shift
+    ;;
+  --no-store-on-disk)
+    options="$options --no-store-on-disk"
+    shift
+    ;;
+  --consistency=*)
+    consistency=${1#*=}
+    options="$options --consistency=$consistency"
+    shift
+    ;;
+  *)
+    echo "Invalid option: $1. Use: --store-on-disk, --no-store-on-disk, --consistency=[0.0-1.0]"
+    exit 1
+    ;;
   esac
 done
 
